___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid"
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [2]:
import numpy as np 



### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [9]:
my_list = [5, 10, 15, 20, 25]

my_array2 = np.array(my_list)
my_array2



array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros.

In [11]:
my_array3 = np.zeros((5,5))
my_array3



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [13]:
my_array4 = np.ones((4,4), dtype=int)
my_array4


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [15]:
my_array5 = np.ones((4,4), dtype=int) * 7
my_array5


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [17]:
my_array6 = np.full((4,4), 7, dtype=int)
my_array6



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive).

In [19]:
my_array7 = np.arange(2,17,2)
my_array7



array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [21]:
my_array8 = np.arange(25).reshape(5, 5)
my_array8


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [23]:
my_array9 = np.linspace(0, 24, 25, dtype=int).reshape(5, 5)
my_array9



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [27]:
my_ran_5_array = np.random.rand(5)
my_ran_5_array



array([0.02803031, 0.76492913, 0.66286   , 0.34674335, 0.05930288])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [29]:
my_std_dn_array = np.random.randn(5, 5)
my_std_dn_array


array([[-1.68361294, -1.04959922, -0.29359463, -0.49440204, -0.88720613],
       [-0.45298675, -0.11095955, -1.13377902,  0.28454779,  0.35042268],
       [ 0.07242566,  0.08269978,  1.80906164,  0.04236895,  0.06244398],
       [ 0.92586613,  0.92036146, -0.87415626,  1.89962867, -1.94011396],
       [-1.72873009,  0.15985074,  1.84297328,  0.02394531,  0.35256432]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [31]:
my_array = np.random.randint(20, 51, size=(3,4))
my_array



array([[38, 32, 46, 20],
       [33, 42, 21, 39],
       [43, 37, 41, 39]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [33]:
ranarr = np.random.randint(0, 56, 48)
ranarr



array([35, 44,  6,  7, 37,  2,  0, 23, 46, 23, 15,  0, 34, 26, 47, 44, 15,
       37, 14, 44, 54,  8,  7, 14, 35, 35, 49, 10, 35, 12, 21, 41, 42, 12,
       24, 13, 28, 54, 10, 45,  0,  1, 29, 31, 54, 43, 27, 40])

In [37]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr = np.random.randint(0, 56, 48)
my_array = ranarr.reshape(6, 8)
my_array


array([[34, 20, 46, 20, 24, 48, 35, 13],
       [ 5, 29, 21, 23, 48, 38, 12, 53],
       [ 8, 27,  0, 15, 12, 32, 14, 45],
       [23, 29, 32, 23, 55, 51, 16, 40],
       [17, 54, 36, 26, 46, 16, 34, 50],
       [54, 24, 54, 55, 33, 41, 19,  8]])

In [39]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
ranarr = np.random.randint(0, 56, 48)
my_array = ranarr.reshape(-1, 8)
my_array


array([[49, 12,  2, 12, 38, 45, 46, 26],
       [51, 31,  3, 20, 43,  6, 13, 15],
       [31, 48,  0, 38, 45, 21,  1, 38],
       [ 5, 48,  2, 43, 46, 47,  3,  4],
       [11, 37, 20,  5,  0,  0, 53,  6],
       [16, 16, 53, 42,  3, 34, 54, 30]])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH -1)



## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [95]:
mat = np.arange(1, 17).reshape(4, 4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [98]:
alt_array = mat[1:3, 1:3]
alt_array


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [101]:
ilk_sutun = mat[:, 0]
ilk_sutun


array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [104]:
get_array = mat[1, ::2]
get_array


array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [107]:
mat_copy = mat.copy()

mat_copy[:, 2] = 77
mat_copy


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [51]:
my_array = np.array([mat[1, 0], mat[3, 2]])
my_array


array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [53]:
my_array = np.array(mat[1::2, [0, 2]])
my_array


array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [109]:
# LET US REMEMBER OUR ARRAY OF "mat"

mat_copy



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [115]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat"

my_values1 = mat_copy[(mat_copy < 10)]
my_values1



array([1, 2, 4, 5, 6, 8, 9])

In [119]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat"

my_values2 = mat_copy[(mat_copy > 12)]
my_values2



array([77, 77, 77, 13, 14, 77, 16])

In [61]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat"

my_last_values = np.array([x + y for x, y in zip(my_values1, my_values2)])
my_last_values



array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [65]:
my_std = np.std(my_last_values)
my_std



29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [121]:
# LET US REMEMBER OUR ARRAY OF "mat"

mat_copy



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [123]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat"

mat



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [125]:
sum_2_coulumn = np.sum(mat[:, 1])
sum_2_coulumn



32

### 23. Get the median, mean and std of 3rd column in "mat".

In [129]:
# LET US REMEMBER OUR ARRAY OF "mat"

mat



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [131]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE

my_3rd_coulumn = mat[:, 2].reshape(-1, 1) 
my_3rd_coulumn



array([[ 3],
       [ 7],
       [11],
       [15]])

In [133]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW?

my_3rd_row = mat[2,:].reshape(1,-1)
my_3rd_row



array([[ 9, 10, 11, 12]])

In [135]:
# LET US GET MEDIAN VALUE

med1 = np.median(my_3rd_coulumn)
med1

med2 = np.median(my_3rd_row)
med2

print(med1)
print(med2)



9.0
10.5


In [137]:
# LET US GET MEAN VALUE

mea1 = np.mean(my_3rd_coulumn)
mea1

mea2 = np.mean(my_3rd_row)
mea2

print(mea1)
print(mea2)

9.0
10.5


In [139]:
# LET US GET STANDART DEVIATION (std) VALUE

std1 = np.std(my_3rd_coulumn)
mea1

std2 = np.std(my_3rd_row)
mea2

print(std1)
print(std2)

4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [143]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

[pandas.read_csv() function --> (pandas official document)](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

In [147]:
!pip install py7zr

import py7zr
with py7zr.SevenZipFile('Salaries.7z', mode='r') as z:
    z.extractall()

In [149]:
# LET US READ Salaries.csv

df = pd.read_csv('Salaries.csv')
df



Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [151]:
# LET US LOOK AT THE FIRST 5 ROWS

df.head()



Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [153]:
# LET US GET A SAMPLE

df.sample()



Id      EmployeeName            JobTitle    BasePay  OvertimePay  \
2538  2539  MARK TRIERWEILER  POLICE OFFICER III  112401.08     26433.73   

      OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
2538   7280.32       NaN  146115.13         146115.13  2011    NaN   

             Agency  Status  
2538  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [155]:
df.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [157]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS

df.describe()



Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [159]:
year_counts = df["Year"].value_counts().sort_index(ascending=False).rename('Year')
year_counts



Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [161]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

unique_years = df['Year'].nunique()
unique_years



4

In [163]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

df['Year'].unique()



array([2011, 2012, 2013, 2014], dtype=int64)

### Print out max and avg values in the column of "Totalpay".

In [165]:
# LET US FIND THE MAXIMUM TOTALPAY

max_totalPay = df['TotalPay'].max()
max_totalPay



567595.43

In [167]:
# LET US FIND THE AVERAGE TOTALPAY

avg_totalPay = df['TotalPay'].mean()
avg_totalPay



74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [171]:
df_greater_than_avg = df[df['TotalPay'] > avg_totalPay]
df_greater_than_avg


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [173]:
ave_totalPay = df['TotalPay'].mean()

count_greater_than_avg = (df['TotalPay'] >ave_totalPay).sum()
count_greater_than_avg 



69489

### How much does ALBERT PARDINI make money (including benefits)?

In [175]:
albert_salary_series = df.loc[df['EmployeeName'] == 'ALBERT PARDINI', 'TotalPayBenefits']
albert_salary_series



2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [177]:
min_salary_person = df.loc[df['TotalPayBenefits'] == df['TotalPayBenefits'].min(), 'EmployeeName']
min_salary_person



148653    Joe Lopez
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [179]:
unique_job_titles = df['JobTitle'].unique()
unique_job_titles



array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [181]:
least_common_jobs = df['JobTitle'].value_counts().tail(3).rename('JobTitle')
least_common_jobs



JobTitle
COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

In [185]:
# 1 SOLUTION :

(df[df['Year'] == 2012]['TotalPayBenefits'] > df[df['Year'] == 2012]['TotalPayBenefits'].mean()).sum()



18703

In [187]:
# 2 SOLUTION :

df_2012 = df[df['Year'] == 2012]
average_2012 = df_2012['TotalPayBenefits'].mean()
ust_average_2012 = df_2012[df_2012['TotalPayBenefits'] > average_2012]
len(ust_average_2012)



18703

### How many people have a title of Manager in their jobs?

In [189]:
# USE APPLY FUNCTION

df['JobTitle'].str.contains('Manager', case=False, na=False).sum()



4110

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [191]:
sal_new = df.iloc[:, [0, 1, 2, 7, 8]]
sal_new



Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [193]:
sal_new = df.loc[:, ['EmployeeName', 'JobTitle', 'TotalPay', 'TotalPayBenefits']]
sal_new



EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [195]:
sal_new = df.loc[(df['TotalPayBenefits'] > df['TotalPayBenefits'].min()) & (df['TotalPayBenefits'] < df['TotalPayBenefits'].mean()), ['EmployeeName', 'TotalPayBenefits']]

sal_new



EmployeeName  TotalPayBenefits
10806          KWE LEE          93691.15
10807   MIGUEL CARO JR          93682.74
10808    JOANNE MORRIS          93680.53
10809    LAYLA WELBORN          93676.88
10810          LE BANH          93675.39
...                ...               ...
148648     Leon Walker              0.00
148649   Roy I Tillery              0.00
148650    Not provided              0.00
148651    Not provided              0.00
148652    Not provided              0.00

[75649 rows x 2 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid"
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________